### PR TITLE
feat(httpSignature): support httpSignature

### PR DESCRIPTION
**Pull request by hekike**
- [x] add httpSignature support

### CODE REVIEW

**Comment by dustinsmith1024** [comment]
looks good to me - @doug-martin you want to review?  I can merge and publish if you like.

**Comment by hekike** [comment]
@dustinsmith1024 @doug-martin any progress with the review? We have been using it for 3 days and works very well ;)

**Comment by doug-martin** [comment]
Looks good

**Comment by dustinsmith1024** [comment]
I just pushed 1.1.0 to npm.  Thanks for the PR @hekike.

**Comment by hekike** [comment]
@dustinsmith1024 thanks!

**Pull request merged**
